const lessonTitle = "老渔夫";

const lessonData = [
    // 正文第 1 段
    ["我们家", "wǒ men jiā", "our home", "rumah kami"],
    ["位于", "wèi yú", "located at", "terletak di"],
    ["约翰·霍普金斯医院", "yuē hàn · huò pǔ jīn sī yī yuàn", "Johns Hopkins Hospital", "Hospital Johns Hopkins"],
    ["的", "de", "particle", ""],
    ["对面", "duì miàn", "opposite", "sebelah bertentangan / depan"],
    ["。", "", "", ""],
    ["和", "hé", "with / and", "dengan / dan"],
    ["附近的", "fù jìn de", "nearby's", "berhampiran punya"],
    ["有些", "yǒu xiē", "some", "beberapa"],
    ["居民", "jū mín", "residents", "penduduk"],
    ["一样", "yí yàng", "the same", "sedemikian / sama"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["把", "bǎ", "structural particle", ""],
    ["楼上的", "lóu shàng de", "upstairs'", "tingkat atas punya"],
    ["房间", "fáng jiān", "rooms", "bilik"],
    ["出租给", "chū zū gěi", "rent out to", "menyewakan kepada"],
    ["医院的", "yī yuàn de", "hospital's", "hospital punya"],
    ["门诊病人", "mén zhěn bìng rén", "outpatients", "pesakit luar"],
    ["，", "", "", ""],
    ["楼下的", "lóu xià de", "downstairs'", "tingkat bawah punya"],
    ["则", "zé", "then / on the other hand", "maka / pula"],
    ["留给", "liú xià gěi", "leave for", "simpan untuk"],
    ["自己", "zì jǐ", "oneself", "diri sendiri"],
    ["居住", "jū zhù", "live / reside", "tinggal / mendiami"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["一个", "yí gè", "A / one", "Seorang / suatu"],
    ["夏天的", "xià tiān de", "summer's", "musim panas punya"],
    ["傍晚", "bàng wǎn", "evening / dusk", "senja / lewat petang"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["正忙着", "zhèng zài māng zhe", "was busy doing", "sedang sibuk"],
    ["为", "wèi", "for", "untuk"],
    ["家人", "jiā rén", "family members", "ahli keluarga"],
    ["准备", "zhǔn bèi", "prepare", "menyediakan"],
    ["晚餐", "wǎn cān", "dinner", "makan malam"],
    ["。", "", "", ""],
    ["突然", "tū rán", "suddenly", "Tiba-tiba"],
    ["，", "", "", ""],
    ["门铃", "mén líng", "doorbell", "loceng pintu"],
    ["响了起来", "xiǎng le qǐ lái", "rang out", "berbunyi"],
    ["，", "", "", ""],
    ["外面", "wài mian", "outside", "di luar"],
    ["站着", "zhàn zhe", "standing", "berdiri"],
    ["一个", "yí gè", "a (person)", "seorang"],
    ["满脸倦容", "mǎn liǎn juàn róng", "face full of exhaustion / weary face", "muka yang sangat letih"],
    ["，", "", "", ""],
    ["衣着简朴", "yī zhuó jiǎn pǔ", "plainly dressed", "berpakaian ringkas / sederhana"],
    ["、", "", "", ""],
    ["瘦小干枯的", "shòu xiǎo gān kū de", "thin, small and withered", "kurus kecil dan kering ceking"],
    ["驼背", "tuó bèi", "hunchback", "bongkok"],
    ["老人", "lǎo rén", "old man", "orang tua"],
    ["，", "", "", ""],
    ["最为", "zuì wéi", "most", "paling"],
    ["骇人的是", "hài rén de shì", "shocking / frightening is that", "menakutkan adalah"],
    ["他那张脸", "tā nà zhāng liǎn", "his that face", "dia punya muka yang itu"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["红肿", "hóng zhǒng", "red and swollen", "merah dan bengkak"],
    ["而", "ér", "and thereby", "lalu"],
    ["严重", "yán zhòng", "seriously / severely", "amat / sangat serius"],
    ["不对称", "bú duì chèng", "asymmetrical / out of proportion", "tidak sepadan / senget sebelah"],
    ["。", "", "", ""],
    ["然而", "rán ér", "However / yet", "Namun begitu / sebaliknya"],
    ["，", "", "", ""],
    ["他的", "tā de", "his", "dia punya"],
    ["声音", "shēng yīn", "voice", "suara"],
    ["却", "què", "however", "pula / sebaliknya"],
    ["很", "hěn", "very", "sangat"],
    ["和蔼友善", "hé ǎi yǒu shàn", "amiable and friendly", "ramah dan baik hati / mesra"],
    ["，", "", "", ""],
    ["他说", "tā shuō", "he said", "dia berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["晚上好", "wǎn shàng hǎo", "Good evening", "Selamat petang"],
    ["，", "", "", ""],
    ["太太", "tài tai", "Madam / Mrs", "puan"],
    ["。", "", "", ""],
    ["我来这里", "wǒ lái zhè lǐ", "I come here to", "Saya datang ke sini untuk"],
    ["看看", "kàn kan", "look and see", "melihat-lihat sama ada"],
    ["有没有", "yǒu méi ___", "if there is any", "ada atau tidak"],
    ["房间", "fáng jiān", "room", "bilik"],
    ["出租", "chū zū", "rent out", "disewakan"],
    ["，", "", "", ""],
    ["我只住", "wǒ zhǐ zhù", "I only stay for", "saya hanya tinggal"],
    ["一个晚上", "yí gè wǎn shàng", "one night", "satu malam sahaja"],
    ["。", "", "", ""],
    ["我从", "wǒ cóng", "I from", "Saya dari"],
    ["东海岸", "dōng hǎi àn", "East Coast", "Pantai Timur"],
    ["来此", "lái cǐ", "come here to", "datang ke sini untuk"],
    ["求医", "qiú yī", "seek medical treatment", "mendapatkan rawatan ubat"],
    ["，", "", "", ""],
    ["回去的", "huí qù de", "returning's", "untuk pulang punya"],
    ["公车", "gōng chē", "bus", "bas awam"],
    ["要", "yào", "need to / will only", "hanya akan ada"],
    ["明早", "míng zǎo", "tomorrow morning", "pagi esok"],
    ["才有", "cái yǒu", "then have", "baru ada"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["他从", "tā cóng", "He from", "Dia sejak dari"],
    ["中午", "zhōng wǔ", "noon / midday", "tengah hari"],
    ["开始", "kāi shǐ", "started", "mula"],
    ["找", "zhǎo", "look for", "mencari"],
    ["住宿的", "zhù sù de", "accommodation's", "tempat tinggal punya"],
    ["地方", "dì fāng", "place", "kawasan / tempat"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi / namun"],
    ["没人", "méi rén", "nobody", "tiada sesiapa pun"],
    ["愿意", "yuàn yì", "willing to", "sudi / rela"],
    ["接纳他", "jiē nà tā", "accept him", "menerima dia tinggal"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["我猜", "wǒ cāi", "I guess", "Saya rasa"],
    ["都是因为", "dōu shì yīn wèi", "all because of", "semuanya adalah disebabkan"],
    ["我的脸", "wǒ de liǎn", "my face", "muka saya"],
    ["。", "", "", ""],
    ["不过", "bú guò", "But / however", "Namun begitu / tetapi"],
    ["医生说", "yī shēng shuō", "doctor said", "doktor berkata"],
    ["，", "", "", ""],
    ["它会", "tā huì", "it will", "ia akan"],
    ["好起来的", "hǎo qǐ lái de", "get better", "menjadi sembuh semula"],
    ["。”", "", "", ""],
    ["说实话", "shuō shí huà", "To tell the truth", "Sejujurnya / cakap benar"],
    ["，", "", "", ""],
    ["当时候的", "dāng shí hòu de", "at that time's", "pada masa itu punya"],
    ["我", "wǒ", "I", "saya"],
    ["也有些", "yě yǒu xiē", "also had some", "pun ada sedikit"],
    ["犹豫不决", "yóu yù bù jué", "hesitant / undecided", "berbelah bahagi / teragak-agak"],
    ["。", "", "", ""],
    ["但是", "dàn shì", "But", "Namun"],
    ["老人的", "lǎo rén de", "old man's", "orang tua itu punya"],
    ["诚恳", "chéng kěn", "sincerity", "keikhlasan / ketulusan hati"],
    ["最终", "zuì zhōng", "eventually / in the end", "akhirnya"],
    ["还是", "hái shì", "still", "tetap"],
    ["打动了", "dǎ dòng le", "moved / touched", "menyentuh hati / menggerakkan心"],
    ["我", "wǒ", "me", "saya"],
    ["。", "", "", ""],
    ["晚饭", "wǎn fàn", "Dinner", "Makan malam"],
    ["做好", "zuò hǎo", "done / ready", "selesai dimasak"],
    ["后", "hòu", "after", "selepas itu"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["邀请", "yāo qǐng", "invited", "menjemput / mengundang"],
    ["老人", "lǎo rén", "old man", "orang tua itu"],
    ["一起", "yì qǐ", "together", "bersama-sama"],
    ["进餐", "jìn cān", "dine / eat meal", "makan nasi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["“", "", "", ""],
    ["不了", "bù liǎo", "No, thanks", "Tidak usahlah"],
    ["，", "", "", ""],
    ["谢谢你们的", "xiè xie nǐ men de", "thank you for your", "terima kasih atas kalian punya"],
    ["好意", "hǎo yì", "kindness / good intention", "niat baik / kebaikan hati"],
    ["，", "", "", ""],
    ["我自己", "wǒ zì jǐ", "I myself", "saya sendiri"],
    ["准备了", "zhǔn bèi le", "prepared", "telah menyediakan"],
    ["食物", "shí wù", "food", "makanan"],
    ["。”", "", "", ""],
    ["老人", "lǎo rén", "The old man", "Orang tua itu"],
    ["笑着", "xiào zhe", "smilingly", "sambil tersenyum"],
    ["向我们", "xiàng wǒ men", "towards us", "kepada kami"],
    ["摇了摇", "yáo le yáo", "waved / shook", "menggoyang-goyangkan"],
    ["手中", "shǒu zhōng", "in hand", "dalam tangan"],
    ["的", "de", "particle", ""],
    ["棕色", "zōng sè", "brown", "warna coklat"],
    ["纸袋", "zhǐ dài", "paper bag", "beg kertas"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["晚饭", "wǎn fàn", "Dinner", "Makan malam"],
    ["过后", "hòu", "after", "selepas itu"],
    ["，", "", "", ""],
    ["我和", "wǒ hé", "I and", "saya dengan"],
    ["老人", "lǎo rén", "old man", "orang tua itu"],
    ["聊了", "liáo le", "chatted for", "berbual-bual"],
    ["一会儿", "yí huì r", "a moment", "sebentar"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["发现", "fā xiàn", "discovered / found", "mendapati / menyedari"],
    ["，", "", "", ""],
    ["在他", "zài tā", "in his", "di dalam dia punya"],
    ["瘦小的", "shòu xiǎo de", "thin and small", "tubuh yang kurus kecil"],
    ["身躯", "shēn qū", "body / stature", "badan / susuk tubuh"],
    ["里", "lǐ", "inside", "dalam"],
    ["包含着", "bāo hán zhe", "contained / contained within", "mempunyai / mengandungi sarat"],
    ["格外", "gé wài", "especially / exceptionally", "amat / sangat / luar biasa"],
    ["宽广的", "kuān guǎng de", "broad / wide / vast", "luas terbentang punya"],
    ["胸怀", "xīn huái", "mind / heart / breadth of mind", "hati / jiwa / lapang dada"],
    ["。", "", "", ""],
    ["他以", "tā yǐ", "He by means of", "Dia dengan cara"],
    ["打鱼", "dǎ yú", "fishing", "menangkap ikan"],
    ["为生", "wéi shēng", "make a living", "sebagai rezeki hidup"],
    ["，", "", "", ""],
    ["养活着", "yǎng huó zhe", "supporting / feeding", "menyara kehidupan"],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["、", "", "", ""],
    ["女婿", "nǚ xu", "son-in-law", "menantu lelaki"],
    ["以及", "yǐ jí", "as well as", "serta"],
    ["他们的", "tā men de", "their", "mereka punya"],
    ["五个孩子", "wǔ gè hái zi", "five children", "lima orang anak"],
    ["。", "", "", ""],
    ["女婿", "nǚ xu", "The son-in-law", "Menantu lelaki itu"],
    ["因伤", "yīn shāng", "due to injury", "disebabkan cedera / luka"],
    ["而", "ér", "and thereby", "lalu"],
    ["丧失了", "sàng shī le", "lost", "kehilangan / hilang langsung"],
    ["劳动能力", "láo dòng néng lì", "ability to work / labor capacity", "keupayaan untuk bekerja"],
    ["，", "", "", ""],
    ["他本人", "tā zì jǐ", "he himself", "dia sendiri pula"],
    ["却", "què", "yet / surprisingly", "sebaliknya"],
    ["患上", "huàn shàng", "contracted / suffered from", "menghidapi / mendapat sakit"],
    ["一种", "yì zhǒng", "a kind of", "sejenis"],
    ["罕见的", "hǎn jiàn de", "rare", "yang jarang ditemui / pelik"],
    ["皮肤病", "pí fū bìng", "skin disease", "penyakit kulit"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "namun / tetapi"],
    ["言谈之间", "yán tán zhī jiān", "during the conversation / in his words", "dalam perbualan kata-katanya"],
    ["，", "", "", ""],
    ["老人", "lǎo rén", "the old man", "orang tua itu"],
    ["没有", "méi yǒu", "did not have", "langsung tidak ada"],
    ["丝毫的", "sī háo de", "the slightest hint of", "sedikit pun perasaan"],
    ["怨天尤人", "yuàn tiān yóu rén", "blame God and man / grumble against fate", "menyalahkan takdir atau merungut kepada orang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["第二天", "dì èr tīan", "The next day", "Keesokan harinya"],
    ["早晨", "zǎo chen", "morning", "pagi"],
    ["起来", "qǐ lái", "woke up / getting up", "bangun tidur"],
    ["，", "", "", ""],
    ["老人", "lǎo rén", "old man", "orang tua itu"],
    ["已经在", "yǐ jīng zài", "already at", "sudah pun berada di"],
    ["院子里", "yuàn zi lǐ", "inside the yard", "dalam halaman rumah"],
    ["等着我们", "děng zhe wǒ men", "waiting for us", "sedang menunggu kami"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],
    ["临别之际", "lín bié zhī jì", "at the moment of parting", "Ketika saat mengucapkan selamat tinggal"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["吞吞吐吐地", "tūn tūn tǔ tǔ de", "stutteringly / hesitatingly in speech", "dengan tersangkut-sangkut cakap / malu-malu"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["下次", "xià cì", "Next time", "Kali akan datang"],
    ["我来看病", "wǒ lái kàn bìng", "I come for medical treatment", "saya datang dapat ubat / jumpa doktor"],
    ["，", "", "", ""],
    ["还能", "hái néng", "still can", "masih bolehkah"],
    ["住", "zhù", "stay at", "tinggal di"],
    ["你们这里", "nǐ men zhè lǐ", "your place here", "tempat kalian di sini"],
    ["吗", "ma", "particle", "kah"],
    ["？", "", "", ""],
    ["我不会", "wǒ bú huì", "I will not", "saya tidak akan"],
    ["给你们", "gěi nǐ men", "to you all", "kepada kalian"],
    ["添很多麻烦的", "tiān hěn duō má fan de", "add a lot of trouble", "menambah banyak kesusahan / menyusahkan"],
    ["。”", "", "", ""],
    ["停顿了", "tíng dùn le", "paused for", "Berhenti seketika"],
    ["一下", "yí xià", "a brief moment", "sekejap"],
    ["，", "", "", ""],
    ["他又", "tā yòu", "he again", "dia pula"],
    ["补充道", "bǔ chōng dào", "supplemented / added", "menambah ulasan berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你们的", "nǐ men de", "your all's", "Kalian punya"],
    ["孩子", "hái zi", "children", "anak-anak"],
    ["让我", "ràng wǒ", "make me", "membuatkan saya"],
    ["感觉", "gǎn jué", "feel", "berasa"],
    ["就像", "jiù xiàng", "just like", "bagaikan"],
    ["回到了", "huí dào le", "returned to", "pulang balik ke"],
    ["家里", "jiā lǐ", "home", "rumah sendiri"],
    ["。", "", "", ""],
    ["大人们", "dà rén men", "Adults", "Orang-orang dewasa"],
    ["讨厌", "tǎo yàn", "loathe / detest", "membenci / tidak suka"],
    ["我的脸", "wǒ de liǎn", "my face", "muka saya"],
    ["，", "", "", ""],
    ["孩子们", "hái zi men", "children", "manakala anak-anak kecil"],
    ["却", "què", "yet / but", "sebaliknya"],
    ["不那么", "bù nà me", "not that much", "tidaklah begitu"],
    ["在意", "zài yì", "mind / care about", "mengambil kisah / peduli"],
    ["。”", "", "", ""],
    ["我们", "wǒ men", "We", "Kami"],
    ["表示", "biǎo shì", "expressed / indicated", "menyatakan tanda"],
    ["欢迎他", "huān yíng tā", "welcome him", "mengalu-alukan dia"],
    ["下次", "xià cì", "next time", "kali depan"],
    ["再来", "zài lái", "come again", "datang lagi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["第二次", "dì èr cì", "The second time", "Kali kedua"],
    ["，", "", "", ""],
    ["老人", "lǎo rén", "the old man", "orang tua itu"],
    ["大约在", "dà yuē zài", "approximately at", "kira-kira pada pukul"],
    ["早上", "zǎo chen", "morning", "pagi"],
    ["七点钟", "qī diǎn zhōng", "seven o'clock", "tujuh jam"],
    ["就", "jiù", "already / as early as", "pun terus"],
    ["来到", "lái dào", "arrived at", "sampai ke"],
    ["我们家", "wǒ men jiā", "our home", "rumah kami"],
    ["。", "", "", ""],
    ["他还", "tā hái", "he also", "Dia juga"],
    ["带来了", "dài lái le", "brought along", "membawa bersama"],
    ["一条", "yì tiáo", "one (measure word for fish)", "seekor"],
    ["大鱼", "dà yú", "big fish", "ikan besar"],
    ["和", "hé", "and", "dan"],
    ["一袋", "yí dài", "a bag of", "sebeg"],
    ["牡蛎", "mǔ lì", "oysters", "tiram (makanan laut)"],
    ["作为", "wéi zuò", "as", "sebagai"],
    ["礼物", "lǐ wù", "gift / present", "hadiah"],
    ["。", "", "", ""],
    ["为了", "wèi le", "In order to", "Untuk"],
    ["保持", "bǎo chí", "maintain / keep", "mengekalkan"],
    ["牡蛎的", "mǔ lì de", "oysters'", "tiram punya"],
    ["新鲜", "xīn xiān", "freshness / fresh", "kesegaran"],
    ["，", "", "", ""],
    ["当天", "dāng tiān", "that same day's", "pada hari itu punya"],
    ["早上", "zǎo chen", "morning", "pagi-pagi"],
    ["出发", "chū fā", "set out / depart", "bertolak"],
    ["之前", "zhī qián", "before", "sebelum"],
    ["，", "", "", ""],
    ["他才把", "tā cái bǎ", "he only then object particle", "barulah dia menyebabkan"],
    ["牡蛎", "mǔ lì", "oysters", "tiram itu"],
    ["剥壳", "bō ké", "shuck / shell", "dikupas kulitnya"],
    ["。", "", "", ""],
    ["而他", "ér tā", "And he / while his", "Manakala dia punya"],
    ["所乘的", "suǒ chéng de", "taken's", "yang dinaiki punya"],
    ["公车", "gōng chē", "bus", "bas awam"],
    ["在", "zài", "at", "pada pukul"],
    ["凌晨", "lín chén", "early morning before dawn", "dinihari / sebelum subuh"],
    ["四点", "sì diǎn", "four o'clock", "empat jam"],
    ["就", "jiù", "already", "pun terus"],
    ["出发", "chū fā", "departed / set out", "bertolak"],
    ["，", "", "", ""],
    ["那他", "nà tā", "then he", "maka dia"],
    ["几点", "jǐ diǎn", "what time", "pukul berapa"],
    ["就", "jiù", "already", "pun"],
    ["起床了", "qǐ chuáng le", "got out of bed", "dah bangun tidur"],
    ["呢", "ne", "particle", "ya"],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["以后", "yǐ hòu", "From then on / afterwards", "Semenjak dari hari itu / selepas itu"],
    ["，", "", "", ""],
    ["老人", "lǎo rén", "the old man", "orang tua itu"],
    ["经常来", "jīng cháng lái", "frequently came to", "sering kali datang ke"],
    ["我们家", "wǒ men jiā", "our home", "rumah kami"],
    ["过夜", "guò yè", "spend the night", "bermalam / bermalam"],
    ["，", "", "", ""],
    ["每次", "měi cì", "every time", "setiap kali"],
    ["他都会", "tā dōu huì", "he all would", "dia pasti akan"],
    ["带给我们", "dài gěi wǒ men", "bring to us", "membawa kepada kami"],
    ["新鲜的", "xīn xiān de", "fresh", "yang segar punya"],
    ["鱼", "yú", "fish", "ikan"],
    ["、", "", "", ""],
    ["牡蛎", "mǔ lì", "oysters", "tiram"],
    ["或者", "huò zhě", "or", "ataupun"],
    ["自家产的", "zì jiā chǎn de", "home-grown / self-produced", "hasil tanaman sendiri punya"],
    ["蔬菜", "shū cài", "vegetables", "sayur-sayuran"],
    ["。", "", "", ""],
    ["有时", "yǒu shí", "Sometimes", "Kadang-kala"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["还会", "hái huì", "still would", "masih juga akan"],
    ["收到", "shōu dào", "receive", "menerima"],
    ["他寄来的", "jì lái de", "sent by him's", "yang dikirim oleh dia punya"],
    ["包裹", "bāo guǒ", "parcel", "bingkisan / paket"],
    ["，", "", "", ""],
    ["而且是", "ér qiě shì", "and moreover it was", "malah ia adalah berbentuk"],
    ["限时专送", "xiàn shí zhuān sòng", "special / express delivery", "hantaran ekspres / segera"],
    ["。", "", "", ""],
    ["为了", "wèi le", "In order to", "Demi untuk"],
    ["邮寄", "yóu jì", "mail / post", "mengeposnya"],
    ["，", "", "", ""],
    ["他要走上", "tā yào zǒu shàng", "he had to walk up to", "dia terpaksa berjalan kaki sejauh"],
    ["3英里", "sān yīng lǐ", "3 miles", "3 batu (kira-kira 4.8 km)"],
    ["的", "de", "particle", ""],
    ["路", "lù", "road / distance", "perjalanan jalan"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["每当", "měi dāng", "Whenever / every time", "Setiap kali"],
    ["我收到", "wǒ shōu dào", "I receive", "saya menerima"],
    ["这样的", "zhè yàng de", "such", "sebegini punya"],
    ["包裹", "bāo guǒ", "parcel", "bingkisan"],
    ["，", "", "", ""],
    ["总会", "zǒng huì", "always will", "pasti akan selalu"],
    ["想起", "xiǎng qǐ", "think of / recall", "teringat semula akan"],
    ["老人", "lǎo rén", "the old man", "orang tua itu"],
    ["第一次", "dì yī cì", "first time", "kali pertama"],
    ["离开", "lí kāi", "leaving", "meninggalkan"],
    ["我们家", "wǒ men jiā", "our home", "rumah kami"],
    ["时", "shí", "when", "waktu itu"],
    ["，", "", "", ""],
    ["邻居", "lín jū", "neighbor", "jiran tetangga bernama"],
    ["露茜", "lù xī", "Lucy (Name)", "Lucy"],
    ["发出后的", "fā chū de", "emitted / expressed's", "yang diucapkan punya"],
    ["感慨", "gǎn kǎi", "sigh / lament / exclamation", "keluhan rasa hairan / kata-kata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你怎么", "nǐ zěn me", "How come you / why did you", "Bagaimanakah kamu boleh"],
    ["收留了", "shōu liú le", "taken in / harboured", "menumpangkan tinggal"],
    ["那个", "nà gè", "that", "orang tua bangka yang"],
    ["长相", "zhǎng xiàng", "appearance / looks", "rupa parasnya"],
    ["可怕的", "kě pà de", "frightening / scary", "menakutkan itu"],
    ["老头", "lǎo tóu", "old man / fellow", "tua"],
    ["？", "", "", ""],
    ["他一靠近", "tā yī kào jìn", "As soon as he approached", "Sebaik sahaja dia mendekati"],
    ["我们家", "wǒ men jiā", "our home", "rumah kami"],
    ["，", "", "", ""],
    ["我就", "wǒ jiù", "I then", "saya terus"],
    ["把它", "bǎ tā", "him (object marker)", "menghala dia / menyebabkan dia"],
    ["打发走了", "dǎ fa zǒu le", "sent away / dismissed", "dihalau pergi jauh"],
    ["！", "", "", ""],
    ["要知道", "yào zhī dào", "You must know / bear in mind", "Perlu kamu tahu"],
    ["，", "", "", ""],
    ["他会", "tā huì", "he will", "dia akan"],
    ["吓跑", "xià pǎo", "scare away", "menakutkan sampai lari"],
    ["其他房客的", "qí tā fáng kè de", "other tenants", "penyewa-penyewa lain punya"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["是的", "shì de", "Yes / indeed", "Ya, memang benar"],
    ["，", "", "", ""],
    ["也许", "yě xǔ", "perhaps / maybe", "barangkali / mungkin"],
    ["我们", "wǒ men", "we", "kami"],
    ["会因此", "huì yīn cǐ", "would because of this", "akan oleh sebab ini"],
    ["失去", "shī qù", "lose", "kehilangan"],
    ["一两个", "yì liǎng gè", "one or two", "seorang dua"],
    ["房客", "fáng kè", "tenants / lodgers", "penyewa"],
    ["，", "", "", ""],
    ["但我们", "dàn wǒ men", "but we all", "namun kami sekeluarga"],
    ["全家", "quán jiā", "whole family", "seluruh keluarga"],
    ["都为", "dōu wèi", "all because of", "semuanya demi"],
    ["认识他", "rèn shi tā", "knowing him", "mengenali beliau berasa"],
    ["高兴", "gāo xìng", "happy / glad", "amat gembira"],
    ["核心", "", "", ""],
    ["内容", "", "", ""],
    ["。", "", "", ""],
    ["从他那里", "cóng tā nà lǐ", "From him", "Daripada pihak beliau"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["学会了", "xué huì le", "learned", "telah menguasai / mempelajari"],
    ["一种", "yì zhǒng", "a kind of", "sejenis"],
    ["宝贵的", "bǎo guì de", "valuable / precious", "yang sangat berharga punya"],
    ["生活态度", "shēng huó tài dù", "attitude towards life", "sikap kehidupan"],
    ["——", "", "", ""],
    ["无论你", "wú lùn nǐ", "no matter what you", "tidak kira apa jua kamu"],
    ["遇到", "yù dào", "encounter / meet", "menghadapi / menemui"],
    ["怎样的", "zěnyàng de", "what kind of", "bagaimana punya"],
    ["不幸", "bú xìng", "misfortune / adversity", "penderitaan / nasib malang"],
    ["，", "", "", ""],
    ["都应该", "dōu yīng gāi", "all should", "tetap harus / sepatutnya"],
    ["学会", "xué huì", "learn to", "belajar untuk"],
    ["坦然地", "tǎn rán de", "calmly / imperturbably", "dengan tenang / berlapang dada"],
    ["接受", "jiē shòu", "accept", "menerima kenyataan / pasrah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段

    ["后来", "hòu lái", "Later on / afterwards", "Kemudian / selepas itu"],
    ["在参观", "zài cān guān", "when visiting", "ketika melawat"],
    ["一位", "yí wèi", "a (measure word for person)", "seorang"],
    ["朋友家的", "péng you jiā de", "friend's home's", "kawan rumah punya"],
    ["暖房植物", "nuǎn fáng zhí wù", "greenhouse plants", "tumbuhan rumah hijau / rumah kaca"],
    ["时", "shí", "when", "waktu / masa"],
    ["，", "", "", ""],
    ["我看到", "wǒ kàn dào", "I saw", "saya melihat"],
    ["在所有", "zài suǒ yǒu", "among all", "dalam kalangan semua"],
    ["花卉中", "huā huì zhōng", "flowers", "bunga-bungaan"],
    ["最美的", "zuì měi de", "the most beautiful", "paling cantik punya"],
    ["金菊花", "jīn jú huā", "marigold / golden chrysanthemum", "bunga kekwa emas"],
    ["，", "", "", ""],
    ["竟然", "jìng rán", "unexpectedly / surprisingly", "rupa-rupanya / rupa-rupanya luar biasa"],
    ["生长在", "shēng zhǎng zài", "growing inside", "hidup membesar di dalam"],
    ["锈迹斑斑的", "xiù jì bān bān de", "rusty / covered in rust spots", "tong besi yang berkarat-karat"],
    ["铁桶里", "tiě tǒng lǐ", "iron bucket", "dalam baldi besi"],
    ["。", "", "", ""],
    ["我告诉", "wǒ gào su", "I told", "Saya memberitahu kepada"],
    ["朋友", "péng you", "friend", "kawan saya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["要是我", "yào shì wǒ", "If it were me", "Sekiranya saya"],
    ["，", "", "", ""],
    ["我一会把", "wǒ huì bǎ", "I would object particle", "saya pasti akan menyebabkan"],
    ["它", "tā", "it", "ia"],
    ["栽种在", "zāi zhòng zài", "plant inside", "ditanam di dalam"],
    ["最漂亮的", "zuì piào liang de", "the most beautiful", "yang paling cantik punya"],
    ["花盆里", "huā pén lǐ", "flowerpot", "pasu bunga"],
    ["。”", "", "", ""],
    ["朋友", "péng you", "The friend", "Kawan itu"],
    ["解释道", "jiě shì dào", "explained", "menerangkan menjelaskan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我这里", "wǒ zhè lǐ", "my place here", "Tempat saya di sini"],
    ["花盆", "hān pén", "flowerpots", "pasu bunga"],
    ["不够多", "bù gòu duō", "not enough", "tidak cukup banyak"],
    ["，", "", "", ""],
    ["我也", "wǒ yě", "I also", "saya pun"],
    ["知道", "zhī dào", "know", "tahu"],
    ["这种花", "zhè zhǒng huā", "this kind of flower", "bunga jenis ini"],
    ["将来", "jiāng lái", "in the future", "pada masa hadapan"],
    ["会", "huì", "will", "akan menjadi"],
    ["非常美", "fēi cháng měi", "extremely beautiful", "amat cantik sekali"],
    ["，", "", "", ""],
    ["但我想", "wǒ xiǎng", "but I think", "tetapi saya rasa"],
    ["它不会", "tā bú huì", "it won't", "ia tidak akan"],
    ["介意", "zài yì", "mind / care", "ambil kisah / kisah"],
    ["在这个", "zài zhè ge", "inside this", "di dalam ini punya"],
    ["旧桶里", "jiù tǒng lǐ", "old bucket", "tong buruk"],
    ["生长", "shēng zhǎng", "grow", "membesar dan hidup"],
    ["核心", "", "", ""],
    ["对账", "", "", ""],
    ["。", "", "", ""],
    ["因为", "yīn wèi", "Because", "Kerana"],
    ["很快", "hěn kuài", "very soon / quickly", "tidak lama lagi / dengan cepat"],
    ["我就会", "wǒ jiù huì", "I will then", "saya akan terus"],
    ["把它", "bǎ tā", "it (object particle)", "menyebabkannya / membawanya"],
    ["移植到", "yí zhí dào", "transplant to", "dipindahkan tanam ke"],
    ["外面的", "wài mian de", "outside's", "luar punya"],
    ["花园", "huā yuán", "garden", "taman bunga"],
    ["去了", "qù le", "go", "sana"],
    ["，", "", "", ""],
    ["那里的", "nà lǐ de", "there's", "di sana punya"],
    ["空间", "kōng jiān", "space", "ruang luar"],
    ["更开阔", "gèng kāi kuò", "more open / broader", "lebih luas lapang"],
    ["、", "", "", ""],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["更充足", "gèng chōng zú", "more abundant", "lebih mencukupi"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["不禁", "bù jīn", "cannot help but", "tidak dapat menahan diri lalu"],
    ["笑了起来", "xiào le qǐ lái", "started laughing", "tertawa sedikit"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["我想到了", "xiǎng dào le", "I thought of", "saya teringat akan"],
    ["那个", "nà gè", "that", "orang tua"],
    ["老人", "lǎo rén", "old man", "itu"],
    ["——", "", "", ""],
    ["他有", "tā yǒu", "he has", "beliau mempunyai"],
    ["一颗", "yì kē", "a (measure word for hearts)", "seulas / sekeping"],
    ["如此美好的", "rú cǐ měi hǎo de", "such a beautiful", "hati yang sebegitu murni dan murni punya"],
    ["心灵", "xīn líng", "soul / heart / mind", "jiwa / sanubari"],
    ["，", "", "", ""],
    ["所以", "suǒ yǐ", "therefore", "oleh itu / jadi"],
    ["不会", "bú huì", "will not", "tidak akan"],
    ["介意", "jiè yì", "mind / care", "berkisah / merungut"],
    ["屈居于", "qū jū yú", "condescend to live in / be confined to", "tinggal mengalah di dalam / tersumbat di"],
    ["一个", "yí gè", "a", "sebuah"],
    ["瘦小的", "shòu xiǎo de", "thin and small", "tubuh yang kurus kecil"],
    ["身体", "shēn tǐ", "body", "badan"],
    ["里", "lǐ", "inside", "dalam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["玛丽·芭特斯·布雷", "mǎ lì · bā tè sī · bù léi", "Mary Bartes Bray (Author)", "Mary Bartes Bray (Penulis)"],
    ["《", "", "", ""],
    ["老渔夫", "lǎo yú fū", "The Old Fisherman", "Nelayan Tua"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
